sudo: false
language: node_js
branches:
  only:
    - /^v\d+\.\d+\.\d+/
node_js:
  - "12"
install:
  - npm install
script:
  - npm run build:icon
  - npm run build
  - npm run build:wx
  - npm run build:docs
before_deploy:
  # get release text
  - npm i markdown-it
  - export RELEASE_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
  - export RELEASE_NOTE=$(node build/deploy/change-log.js --path=docs/docs/changelog.md)
  # get release file
  - mv lib wot-design
  - zip -r wot-design-$RELEASE_NAME-jd.zip wot-design/*
  - mv wot-design lib
  - mv lib-wx wot-design
  - zip -r wot-design-$RELEASE_NAME-wechat.zip wot-design/*
  - mv wot-design lib-wx
deploy:
  provider: <releases>
  # ⋮
  edge: true
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: W9e0MWRF3wxSAzwMPssTclbUIQSDmEKxaguKhRpl4eBKKj7AiVW/hWXgohqo/ADEqff1IPGLK267seIHJHUtAZ7GNc2gRd1BbwYn2Mw5mKNamG72x8Jen2Mhbybxz2bwmITk3BeT96Z7OBuHzTNpY6jUxjq5ApN+7BH8scz/xG7QSLicuzxNlBq+AodhV6u8Y+HvZRzY+Fwijw5NyJ7jWHyFqdYgn9c+T9iRZM4kWfJPMG4opYk1DogzQtqzWXSXPw9anKkTgXEYkhpOnCDgHIn0tQif4CGeDY6m1F+Wftupq4Lmy3NVg6vVfxZO9eYxSGSAMPAlUAnuBdAztObWXjgYHGki/HRLTohswl6dHrIa5Ec/Jg9E9sj93/naUf97a72e8Um2CYMTD7VP5whoR+PtJmB3rS6IEnwqIiI3/8EMlK84iImPq5fQELSSKFqW2DSrm5Qq6XchDhyNbiGG7PWdNTLgcUaISB1qd6edVj6rIktkQANKPbqds1meRQlSwMaXfOPOrXce8oRX9FoFZd9vp4LMXFx2VAVqby+EdeNuJwXamh1nz9pz+kTyD9UEjOJ0GOVzMtLneb2Pnt8aNrbQMLznrRSFCcybJq4sFl1t4dgqkJyARuDN/9CoiW7nOJqZ2sRERJ7WAVlhzUpcUKkC8aT3MUoJUKFseEODPLk=
  name: $RELEASE_NAME
  release_notes: $RELEASE_NOTE
  file_glob: true
  file: ./*.zip
  draft: false
  prerelease: false
  on:
    tags: true
after_deploy:
  - sh ./build/deploy/deploy-docs.sh