sudo: false
language: node_js
branches:
  only:
    - /^v\d+\.\d+\.\d+/
node_js:
  - "12"
install:
  - npm install
script:
  - npm run build:icon
  - npm run build
  - npm run build:wx
  - npm run build:docs
before_deploy:
  # get release text
  - npm i markdown-it
  - export RELEASE_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
  - export RELEASE_NOTE=$(node build/deploy/change-log.js --path=docs/docs/changelog.md)
  # get release file
  - mv lib wot-design
  - zip -r wot-design-$RELEASE_NAME-jd.zip wot-design/*
  - mv wot-design lib
  - mv lib-wx wot-design
  - zip -r wot-design-$RELEASE_NAME-wechat.zip wot-design/*
  - mv wot-design lib-wx
deploy:
  provider: <releases>
  # ⋮
  edge: true
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: SKIoEKvPa5lYLT6YgBYdbmwg2BzJqSP7AVTnMNlRKt7VUFPCpCrkyq6ENFRgfGui/iWoj/6nHebu+63vZRXRx3Gl8XqKuxiRCshKv2dtWhTtPdzP4vmjvg6GeJWazv4YBZplaqkLLEuVJ97VAbIrGATfki2LVZmj1A6y1TIWZsg3KxsgafQH5uZcFdAX+K4lzo/sv/FSV4hbJzKx9QtRC8O1DkJGJpaR1X1GYkv2ZBqwI7DDgwcKIM+jHKalZn7tFPZJMPiqLh2aB+WCVKYJb16jCj5T1t9BuMbYQNVmOCOf2xAB1TQabe4V7ub44wE7pbq1BPj0mwfVSVPZ1nslYfhQtbpXGduoUwRsPa1EIGSw3JCVgc30wW3Xn+1ExDC8N5EBDYKiHKEl6dsIUqnyW7GyzzipsNS9Fy8RK7rQsZc2Gm9oF2oHtsnNlxXeNyfSIKiCNAEHqnvDQXudx6pB/fNR17BU+4p9Juo62UYaXf6UmIDB317H5xtsRsflKDedUEnqLmQZ8KV+LC8UDQ2c8MhOUNdYVcQEfoZSlWlfLhjCzDf8TJMSETIoH+6IeOyH2WFT3THEtlKFjRkkThb1w1zapT6DclK9sqFtlP7X893LDU1byxKdVCDv2mWBZ6p6enTvo4yMV3HH+Hi8BOJ/02xAJM0oyYohqrtoTnie8bk=
  name: $RELEASE_NAME
  release_notes: $RELEASE_NOTE
  file_glob: true
  file: ./*.zip
  draft: false
  prerelease: false
  on:
    tags: true
after_deploy:
  - sh ./build/deploy/deploy-docs.sh